/**
 * styleBulletin — pure function that renders a structured IPL bulletin into
 * HTML matching the existing sport-bulletin look (light gray container,
 * blue headings, simple table styling). Pure: no I/O, no clock, no randomness.
 */

import type { TeamStanding } from './points-table.ts';
import type { Match } from './fixtures-action.ts';

export interface StyleBulletinInput {
  date: string;
  pointsTable: { tournament: string; teams: TeamStanding[] };
  recentMatches: Match[];
  upcomingMatches: Match[];
  predictions: {
    iterations: number;
    playoffProb: Record<string, number>;
    winnerProb: Record<string, number>;
  };
  notes?: string[];
}

export function styleBulletin(input: StyleBulletinInput): string {
  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    `<title>${escape(input.pointsTable.tournament)} Bulletin — ${escape(input.date)}</title>`,
    `<style>${STYLE}</style>`,
    '</head>',
    '<body>',
    '<div class="container">',
    `<h1>${escape(input.pointsTable.tournament)} Bulletin</h1>`,
    `<p class="meta">As of ${escape(input.date)}</p>`,
    renderPointsTable(input.pointsTable.teams),
    renderRecent(input.recentMatches),
    renderUpcoming(input.upcomingMatches),
    renderPredictions(input.predictions),
    renderNotes(input.notes),
    renderFooter(),
    '</div>',
    '</body>',
    '</html>',
  ].join('\n');
}

const STYLE = `
body { font-family: Arial, sans-serif; line-height: 1.6; margin: 0; padding: 20px; color: #333; }
h1, h2 { color: #2c3e50; }
.container { max-width: 900px; margin: auto; background: #f9f9f9; padding: 24px; border-radius: 8px; box-shadow: 0 0 10px rgba(0,0,0,0.08); }
.meta { color: #7f8c8d; font-size: 0.9em; margin-top: -8px; }
table { width: 100%; border-collapse: collapse; margin: 16px 0; background: #fff; }
th, td { border: 1px solid #e1e4e8; padding: 8px 12px; text-align: left; }
th { background: #ecf0f1; }
tr.highlight td { background: #fef9e7; }
.prob-bar { display: inline-block; height: 10px; background: #3498db; vertical-align: middle; border-radius: 2px; }
footer { margin-top: 24px; padding-top: 16px; border-top: 1px solid #ddd; color: #7f8c8d; font-size: 0.85em; }
footer a { color: #2980b9; text-decoration: none; }
`.trim();

function renderPointsTable(teams: TeamStanding[]): string {
  const rows = teams
    .map(
      (t, i) => `<tr${i < 4 ? ' class="highlight"' : ''}>
  <td>${i + 1}</td><td>${escape(t.name)}</td><td>${t.played}</td><td>${t.wins}</td><td>${t.losses}</td><td>${t.points}</td><td>${t.nrr.toFixed(3)}</td>
</tr>`,
    )
    .join('\n');
  return `
<h2>Points Table</h2>
<table>
<thead><tr><th>#</th><th>Team</th><th>P</th><th>W</th><th>L</th><th>Pts</th><th>NRR</th></tr></thead>
<tbody>
${rows}
</tbody>
</table>
`.trim();
}

function renderRecent(matches: Match[]): string {
  if (matches.length === 0) return '';
  const items = matches
    .slice(-5)
    .map((m) => {
      const score = m.score
        ? `${escape(m.score.winner)} won (${m.score.home} vs ${m.score.away})`
        : '—';
      return `<li>${escape(m.date)} — ${escape(m.home)} vs ${escape(m.away)} at ${escape(m.venue)} — <strong>${score}</strong></li>`;
    })
    .join('\n');
  return `<h2>Recent Matches</h2>\n<ul>\n${items}\n</ul>`;
}

function renderUpcoming(matches: Match[]): string {
  if (matches.length === 0) return '';
  const items = matches
    .slice(0, 5)
    .map(
      (m) =>
        `<li>${escape(m.date)} — ${escape(m.home)} vs ${escape(m.away)} at ${escape(m.venue)}</li>`,
    )
    .join('\n');
  return `<h2>Upcoming Matches</h2>\n<ul>\n${items}\n</ul>`;
}

function renderPredictions(p: StyleBulletinInput['predictions']): string {
  const rows = Object.entries(p.winnerProb)
    .sort((a, b) => b[1] - a[1])
    .map(([team, prob]) => {
      const playoff = p.playoffProb[team] ?? 0;
      const widthPct = Math.round(prob * 100);
      return `<tr>
  <td>${escape(team)}</td>
  <td>${(playoff * 100).toFixed(2)}%</td>
  <td>${(prob * 100).toFixed(2)}%</td>
  <td><span class="prob-bar" style="width:${widthPct * 2}px"></span></td>
</tr>`;
    })
    .join('\n');
  return `
<h2>Monte Carlo Predictions</h2>
<p class="meta">${p.iterations.toLocaleString()} simulated rollouts</p>
<table>
<thead><tr><th>Team</th><th>Playoff</th><th>Winner</th><th></th></tr></thead>
<tbody>
${rows}
</tbody>
</table>
`.trim();
}

function renderNotes(notes?: string[]): string {
  if (!notes || notes.length === 0) return '';
  const items = notes.map((n) => `<li>${escape(n)}</li>`).join('\n');
  return `<h2>Notes</h2>\n<ul>\n${items}\n</ul>`;
}

function renderFooter(): string {
  return `
<footer>
Generated by AdaptiveAgent — see <a href="https://twitter.com/murthyug">@murthyug</a>
</footer>
`.trim();
}

function escape(s: string): string {
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
